1.1.6
antarctica/MeshiPhi pull request #34
Opened 2024-02-16 14:56 UTC by SamuelHall700

# MeshiPhi Pull Request Template

Date: 16/02/2024
Version Number: 1.1.5 -> 1.1.6
 
## Description of change
Merging in Visual_iced dataloader, docs upates and additional features added when onboard the ship. Rebuilt the docs so as to be hosted correctly on GitHub

## Fixes # (issue)

# Testing
To ensure that the functionality of the MeshiPhi codebase remains consistent throughout the development cycle a testing strategy has been developed, which can be viewed in the document `test/testing_strategy.md`. 
This includes a collection of test files which should be run according to which part of the codebase has been altered in a pull request. Please consult the testing strategy to determine which tests need to be run. 

- [x] My changes have not altered any of the files listed in the testing strategy

- [ ] My changes result in all required regression tests passing without the need to update test files.  
  
> *list which files have been altered and include a pytest.txt file for each of
> the tests required to be run*
>
> The files which have been changed during this PR can be listed using the command

    git diff --name-only 1.1.x

- [ ] My changes require one or more test files to be updated for all regression tests to pass.   

> *include pytest.txt file showing which tests fail.*  
> *include reasoning as to why your changes cause these tests to fail.* 
>
> Should these changes be valid, relevant test files should be updated.  
> *include pytest.txt file of test passing after test files have been updated.*

# Checklist

- [x] My code follows [pep8](https://peps.python.org/pep-0008/) style guidelines.  
- [x] I have commented my code, particularly in hard-to-understand areas.  
- [x] I have updated the documentation of the codebase where required.  
- [x] My changes generate no new warnings.   
- [] My PR has been made to the `1.1.x` branch (**DO NOT SUBMIT A PR TO MAIN**)

2024-02-16 15:04 UTC, gecoombs commented on docs/source/sections/Installation.rst
>  The first stage is installing a version of Python 3.9, if you don't have a working version. We suggest installing a working Anaconda distribution from https://www.anaconda.com/products/distribution#m
Should this be edited to remove reference to anaconda/python 3.9? As here: https://github.com/antarctica/PolarRoute/blob/docs_update/docs/source/sections/Installation.rst?plain=1

2024-02-16 15:09 UTC, gecoombs requested changes
The committed contents of `docs/html/` don't match what you'd expect from the docs source. There are some old files in there but more importantly some whole sections are missing e.g. `docs/html/sections/Configuration/Configuration_overview.html`. Does it work for you locally @SamuelHall700? If so, this might be linked to having the docs folder in the .gitignore?

2024-02-16 15:15 UTC, SamuelHall700 commented
> The committed contents of `docs/html/` don't match what you'd expect from the docs source. There are some old files in there but more importantly some whole sections are missing e.g. `docs/html/sections/Configuration/Configuration_overview.html`. Does it work for you locally @SamuelHall700? If so, this might be linked to having the docs folder in the .gitignore? It looks like a similar story on `main` so this is probably also what caused the broken links we saw on the web version yesterday.

everything works locally, but `docs/html/*` being in the `.gitignore` file seemed to be the issue here. I've removed it and rebuilt the docs. It should hopefully work now :)

2024-02-16 15:40 UTC, gecoombs commented
It all works much better now although I noticed the Background/Code Overview section is still written for PolarRoute. Maybe this section can just be removed from the MeshiPhi docs?

2024-02-16 16:02 UTC, SamuelHall700 commented
> It all works much better now although I noticed the Background/Code Overview section is still written for PolarRoute. Maybe this section can just be removed from the MeshiPhi docs?

I've removed this paragraph and rebuilt the docs

2024-02-16 16:31 UTC, gecoombs commented on docs/html/sections/Plotting/mesh_plotting.html
This section appears to be empty. There is an automodule statement but no content appears in the html file

2024-02-16 16:52 UTC, gecoombs commented on README.md
> +
Is it an intentional change to have all of these buttons appear on separate lines?

2024-02-19 11:36 UTC, gecoombs commented on README.md
> +
Oh actually looks like this is a wider issue with github badges: https://github.com/badges/shields/issues/9978

2024-02-20 13:24 UTC, gecoombs approved these changes
Looks good

2024-02-20 14:15 UTC, merged