Test automation
antarctica/MeshiPhi pull request #66
Opened 2024-05-15 12:44 UTC by hjabbot

# MeshiPhi Pull Request Template

Date: 2024-05-15
Version Number: 2.1.5
 
## Description of change
Automating the process of determining modified files, and running relevant tests for those files. Also retrieves the calculated meshes from regression tests and provides a copy of them to the user, so that they do not need to be recalculated after running tests. Finally, basic plotting functionality has been implemented that will highlight any differences between new and reference tests. 

This PR adds in the 'meshiphi_test' CLI entry point.
Usage: 
`meshiphi_test <branch_to_compare_to>` to just get a summary through the terminal
`meshiphi_test <branch_to_compare_to> -s -p` to save (-s) the failing meshes to ./pytest_meshiphi/ and also save a plot (-p) of the differences between new and reference regression tests

## Fixes #19, #65

# Testing
To ensure that the functionality of the MeshiPhi codebase remains consistent throughout the development cycle a testing strategy has been developed, which can be viewed in the document `test/testing_strategy.md`. 
This includes a collection of test files which should be run according to which part of the codebase has been altered in a pull request. Please consult the testing strategy to determine which tests need to be run. 

- [ ] My changes have not altered any of the files listed in the testing strategy

- [ ] My changes result in all required regression tests passing without the need to update test files.

- [x] My changes require one or more test files to be updated for all regression tests to pass.   

> test_boundary.py was updated, and that change was accidentally folded into this branch
> It was failing because of the recent antimeridian changes that were implemented. Tests have been updated
> to support multipolygon boundary objects, and tests for each method

# Checklist

- [x] My code follows [pep8](https://peps.python.org/pep-0008/) style guidelines.  
- [x] I have commented my code, particularly in hard-to-understand areas.  
- [x] I have updated the documentation of the codebase where required.  
- [x] My changes generate no new warnings.   
- [x] My PR has been made to the `2.1.x` branch (**DO NOT SUBMIT A PR TO MAIN**)

2024-05-15 15:37 UTC, SamuelHall700 requested changes
A few minor edits but otherwise looks good! 

We'll also require an update to the docs for the new CLI entry :)

2024-05-16 09:44 UTC, gecoombs commented on meshiphi/mesh_validation/mesh_comparator.py
> +        # elif return_type in []
Remove commented code if not needed here

2024-05-16 09:45 UTC, gecoombs commented on meshiphi/mesh_validation/mesh_comparator.py
It would be good to add the new optional argument to the docstring

2024-05-16 09:57 UTC, gecoombs commented on tests/unit_tests/test_jgrid.py
Did we decide to remove this file yesterday?

2024-05-16 09:58 UTC, gecoombs commented on tests/unit_tests/test_mesh_builder.py
> +         #  self.env_mesh.save("global_mesh.json")
I guess this can just be deleted rather than left in as a comment?

2024-05-16 10:00 UTC, gecoombs commented on tests/unit_tests/test_scalar_dataloader.py
> +        pass
Are these tests planned to be filled in as part of this PR or in a future PR?

2024-05-16 10:20 UTC, gecoombs commented on tests/unit_tests/test_mesh_builder.py
> +         #  self.env_mesh.save("global_mesh.json")
Ok, happy for this to stay as is if you're planning to look at it on another branch :+1:

2024-05-16 10:47 UTC, SamuelHall700 approved these changes
Looks good!

2024-05-16 12:01 UTC, gecoombs approved these changes
Looks good, will make keeping track of which tests need to be run much simpler :+1:

2024-05-16 12:03 UTC, merged